docs:
  title: "BumiLu users-service API"
  description: >
    This is the API documentation for the BumiLu users-service.
    It provides endpoints for authentication, chat, favorites and reviews management.
  version: "1.0.0"
  openapi_url: "/docs/openapi.json"
  redoc_url: "/docs/redoc"
  swagger_url: "/docs/swagger"
database:
  type: "postgresql+asyncpg"
  host: "postgres"
  port: 5432
  echo: true
  echo_pool: false
  pool_size: 10
  max_overflow: 20
redis:
  host: "redis"
  port: 6379
  store: 0
jwt:
  issuer: "bumilu"
  access_token_ttl_sec: 1800
  refresh_token_ttl_sec: 2592000
cors:
  enabled: false
  allow_origins: [ "*" ]
  allow_credentials: true
  allow_methods: [ "*" ]
  allow_headers: [ "*" ]
run:
  host: "0.0.0.0"
  port: 8000
