services:
  postgres:
    ports:
      - "${DATABASE__PORT}:5432"
  redis:
    ports:
      - "${REDIS__PORT}:6379"
  api:
    volumes:
      - .:/app
    command: >
      uvicorn app.core.presentation.app:app
      --host ${SERVER__HOST}
      --port ${SERVER__PORT}
      --reload
      --reload-dir /app
      --no-access-log
    ports:
      - "${SERVER__PORT}:${SERVER__PORT}"
