name: bumilu-users-service

services:
  api:
    build: .
    restart: unless-stopped
    env_file: [ .env ]
    networks:
      - bumilu
    ports:
      - "${RUN__PORT:-8000}:${RUN__PORT:-8000}" # Remove after traefik is set up

networks:
  bumilu:
