[project]
name = "bumilu-backend"
version = "0.1.0"
description = "Backend for mobile ans web application BumiLu (不迷路), PAB project"
readme = "README.md"
authors = [
    { name = "Belyashik2K", email = "work@belyashik2k.ru" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[all]>=0.129.0",
    "gunicorn>=25.0.3",
    "pydantic-settings[yaml]>=2.13.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.15.1",
]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = ["tests"]
python_files = ["test_*.py"]
pythonpath = ["."]
asyncio_mode = "auto"

[tool.ruff]
src = ["app", "tests"]

line-length = 88
target-version = "py311"

exclude = [
    ".venv", "venv",
    "dist", "build",
    ".mypy_cache", ".pytest_cache",
    ".ruff_cache",
]

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "W", # warnings
    "I", # import sorting
    "B", # bugbear
    "UP", # pyupgrade
    "SIM", # simplify
    "C4", # comprehensions
    "RUF", # ruff
]
ignore = [
    "E203" # black compatibility
]

fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"] # Ignore unused imports in __init__.py files

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
