[project]
name = "bumilu-backend"
version = "0.1.0"
description = "Backend for mobile and web application BumiLu (不迷路), PAB project"
readme = "README.md"
authors = [
    { name = "Belyashik2K", email = "work@belyashik2k.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "aiobotocore>=3.4.0",
    "aiosmtplib>=5.1.0",
    "alembic>=1.18.4",
    "alembic-postgresql-enum>=1.10.0",
    "apscheduler>=3.11.2",
    "apscheduler-dishka>=1.0.0",
    "dishka>=1.8.0",
    "fastapi[all]>=0.129.0",
    "geoalchemy2[shapely]>=0.18.4",
    "httpx>=0.28.1",
    "openai>=2.26.0",
    "polyline>=2.0.4",
    "prometheus-fastapi-instrumentator>=7.1.0",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings[yaml]>=2.13.0",
    "pyjwt>=2.11.0",
    "redis>=7.2.0",
    "sqlalchemy[postgresql-asyncpg]>=2.0.46",
    "taskiq>=0.12.1",
    "taskiq-redis>=1.2.2",
    "timezonefinder[numba]>=8.2.2",
    "uuid6>=2025.0.1",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "mypy>=1.19.1",
    "pre-commit>=4.5.1",
    "pytest>=9.0.0",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.15.1",
    "testcontainers[redis]>=4.15.0",
]

[tool.uv]
default-groups = []

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = ["tests"]
python_files = ["test_*.py"]
pythonpath = ["."]
asyncio_mode = "auto"
markers = [
    "integration: needs external services (e.g. Docker) to run",
]

[tool.ruff]
src = ["app", "tests"]

line-length = 88
target-version = "py311"

exclude = [
    ".venv", "venv",
    "dist", "build",
    ".mypy_cache", ".pytest_cache",
    ".ruff_cache", "migrations",
]

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "W", # warnings
    "I", # import sorting
    "B", # bugbear
    "UP", # pyupgrade
    "SIM", # simplify
    "C4", # comprehensions
    "RUF", # ruff
]
ignore = [
    "E203", # black compatibility
    "E501", # line length
    "RUF001", # slavic characters (eg. "e, ё") in docstrings,
    "RUF003", # russian language in docstrings,
    "B008", # Do not perform function calls in argument defaults
]

fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = [
    "F401", # Ignore unused imports in __init__.py files
    "F403", # Ignore 'from module import *' in __init__.py files
]
"app/core/infrastructure/queue/worker.py" = ["E402"] # Ignore module level import not at top of file in worker.py

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]
exclude = ["migrations"]
disable_error_code = ["prop-decorator"]

[[tool.mypy.overrides]]
module = "apscheduler.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["aiobotocore.*", "botocore.*", "shapely.*"]
ignore_missing_imports = true
