"""Add favourites table

Revision ID: 69b933d9c9fb
Revises: f534b6037703
Create Date: 2026-03-01 10:47:46.988045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b933d9c9fb'
down_revision: Union[str, Sequence[str], None] = 'f534b6037703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('PLACE', name='favourite_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'entity_type', 'entity_id')
    )
    op.create_index('idx_favourites_entity', 'favourites', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_favourites_entity_id'), 'favourites', ['entity_id'], unique=False)
    op.create_index(op.f('ix_favourites_entity_type'), 'favourites', ['entity_type'], unique=False)
    op.create_index(op.f('ix_favourites_user_id'), 'favourites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favourites_user_id'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_entity_type'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_entity_id'), table_name='favourites')
    op.drop_index('idx_favourites_entity', table_name='favourites')
    op.drop_table('favourites')
    # ### end Alembic commands ###
