"""Add marker_color to place category

Revision ID: 8fa95da3d3e0
Revises: 22e47f50675a
Create Date: 2026-04-01 18:14:52.950859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa95da3d3e0'
down_revision: Union[str, Sequence[str], None] = '22e47f50675a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_categories', sa.Column('marker_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_categories', 'marker_color')
    # ### end Alembic commands ###
