"""Make marker_color not null

Revision ID: b93b31b0ab28
Revises: 8fa95da3d3e0
Create Date: 2026-04-01 18:22:50.698498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93b31b0ab28'
down_revision: Union[str, Sequence[str], None] = '8fa95da3d3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place_categories', 'marker_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place_categories', 'marker_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    # ### end Alembic commands ###
