"""Add photos for places

Revision ID: 81571cb2ae48
Revises: b93b31b0ab28
Create Date: 2026-04-02 18:05:15.460635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81571cb2ae48'
down_revision: Union[str, Sequence[str], None] = 'b93b31b0ab28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_photos',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('file_key', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_file_key', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_photos_place_id_places'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_photos'))
    )
    op.create_index(op.f('ix_place_photos_place_id'), 'place_photos', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_photos_place_id'), table_name='place_photos')
    op.drop_table('place_photos')
    # ### end Alembic commands ###
