"""Init tables

Revision ID: f68ee4111143
Revises:
Create Date: 2026-03-03 20:06:57.135314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68ee4111143'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('PLACE', name='favourite_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'entity_type', 'entity_id', name=op.f('pk_favourites'))
    )
    op.create_index('idx_favourites_entity', 'favourites', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_favourites_entity_id'), 'favourites', ['entity_id'], unique=False)
    op.create_index(op.f('ix_favourites_entity_type'), 'favourites', ['entity_type'], unique=False)
    op.create_index(op.f('ix_favourites_user_id'), 'favourites', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'GUEST', name='user_role_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('devices',
    sa.Column('platform', sa.Enum('ANDROID', name='device_platform_enum'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('app_version', sa.VARCHAR(length=32), nullable=False),
    sa.Column('guest_user_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_user_id'], ['users.id'], name=op.f('fk_devices_guest_user_id_users'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_guest_user_id'), 'devices', ['guest_user_id'], unique=False)
    op.create_index(op.f('ix_devices_last_seen_at'), 'devices', ['last_seen_at'], unique=False)
    op.create_table('reviews',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('PLACE', name='review_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviews_author_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'author_id', name='uq_reviews_entity_author')
    )
    op.create_index(op.f('ix_reviews_author_id'), 'reviews', ['author_id'], unique=False)
    op.create_index('ix_reviews_entity', 'reviews', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_reviews_entity_id'), 'reviews', ['entity_id'], unique=False)
    op.create_index(op.f('ix_reviews_entity_type'), 'reviews', ['entity_type'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_auth_sessions_device_id_devices'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_auth_sessions_refresh_token_hash'))
    )
    op.create_index(op.f('ix_auth_sessions_device_id'), 'auth_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_revoked_at'), 'auth_sessions', ['revoked_at'], unique=False)
    op.create_index('ix_auth_sessions_user_device_revoked_at', 'auth_sessions', ['user_id', 'device_id'], unique=False, postgresql_where=sa.text('revoked_at IS NOT NULL'))
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_user_device_revoked_at', table_name='auth_sessions', postgresql_where=sa.text('revoked_at IS NOT NULL'))
    op.drop_index(op.f('ix_auth_sessions_revoked_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_device_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_reviews_entity_type'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_entity_id'), table_name='reviews')
    op.drop_index('ix_reviews_entity', table_name='reviews')
    op.drop_index(op.f('ix_reviews_author_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_devices_last_seen_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_guest_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_index(op.f('ix_favourites_user_id'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_entity_type'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_entity_id'), table_name='favourites')
    op.drop_index('idx_favourites_entity', table_name='favourites')
    op.drop_table('favourites')
    # ### end Alembic commands ###
