"""Fix some unique constraint keys

Revision ID: 84b3485b97a8
Revises: 69b933d9c9fb
Create Date: 2026-03-03 10:54:51.613162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b3485b97a8'
down_revision: Union[str, Sequence[str], None] = '69b933d9c9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('auth_sessions_refresh_token_hash_key'), 'auth_sessions', type_='unique')
    op.create_unique_constraint(op.f('uq_auth_sessions_refresh_token_hash'), 'auth_sessions', ['refresh_token_hash'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_auth_sessions_refresh_token_hash'), 'auth_sessions', type_='unique')
    op.create_unique_constraint(op.f('auth_sessions_refresh_token_hash_key'), 'auth_sessions', ['refresh_token_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
