"""Migrate to place_favourites instead of common favourites

Revision ID: f80ad1ab5531
Revises: 81571cb2ae48
Create Date: 2026-04-04 11:49:03.204053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f80ad1ab5531'
down_revision: Union[str, Sequence[str], None] = '81571cb2ae48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_favourites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_favourites_place_id_places'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_place_favourites_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'place_id', name=op.f('pk_place_favourites'))
    )
    op.create_index('ix_place_favourites_place_id', 'place_favourites', ['place_id'], unique=False)
    op.drop_index(op.f('idx_favourites_entity'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_entity_id'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_entity_type'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_user_id'), table_name='favourites')
    op.drop_table('favourites')
    sa.Enum('PLACE', name='favourite_entity_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PLACE', name='favourite_entity_type_enum').create(op.get_bind())
    op.create_table('favourites',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', postgresql.ENUM('PLACE', name='favourite_entity_type_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'entity_type', 'entity_id', name=op.f('pk_favourites')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'user_id', name=op.f('uq_favourites_entity_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_favourites_user_id'), 'favourites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favourites_entity_type'), 'favourites', ['entity_type'], unique=False)
    op.create_index(op.f('ix_favourites_entity_id'), 'favourites', ['entity_id'], unique=False)
    op.create_index(op.f('idx_favourites_entity'), 'favourites', ['entity_type', 'entity_id'], unique=False)
    op.drop_index('ix_place_favourites_place_id', table_name='place_favourites')
    op.drop_table('place_favourites')
    # ### end Alembic commands ###
