"""Add chats and chat_messages tables

Revision ID: 726755422bc6
Revises: f68ee4111143
Create Date: 2026-03-05 20:35:41.528357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726755422bc6'
down_revision: Union[str, Sequence[str], None] = 'f68ee4111143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Enum('ZH', 'EN', 'RU', name='language_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'WAITING_FOR_AI', 'ESCALATED_TO_ADMIN', 'CLOSED', name='chat_status_enum'), nullable=False),
    sa.Column('last_location_latitude', sa.Float(), nullable=True),
    sa.Column('last_location_longitude', sa.Float(), nullable=True),
    sa.Column('last_message_preview', sa.VARCHAR(length=32), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chats_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.create_index(op.f('ix_chats_status'), 'chats', ['status'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_index('uq_chats_user_id_active', 'chats', ['user_id'], unique=True, postgresql_where=sa.text("status != 'CLOSED'"))
    op.create_table('chat_messages',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('author_type', sa.Enum('USER', 'AI', 'ADMIN', name='author_type_enum'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('location_latitude', sa.Float(), nullable=True),
    sa.Column('location_longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_chat_messages_chat_id_chats'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.create_unique_constraint(op.f('uq_favourites_entity_type'), 'favourites', ['entity_type', 'entity_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_favourites_entity_type'), 'favourites', type_='unique')
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('uq_chats_user_id_active', table_name='chats', postgresql_where=sa.text("status != 'CLOSED'"))
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_status'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
