"""Add fields for close in chats table

Revision ID: 5874714a69d4
Revises: 726755422bc6
Create Date: 2026-03-08 15:20:34.221453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5874714a69d4'
down_revision: Union[str, Sequence[str], None] = '726755422bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('INACTIVITY', name='chat_close_reason_enum').create(op.get_bind())
    op.add_column('chats', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chats', sa.Column('close_reason', postgresql.ENUM('INACTIVITY', name='chat_close_reason_enum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'close_reason')
    op.drop_column('chats', 'closed_at')
    sa.Enum('INACTIVITY', name='chat_close_reason_enum').drop(op.get_bind())
    # ### end Alembic commands ###
