"""Add new value in close_reason enum

Revision ID: 4a5b43769b29
Revises: 5874714a69d4
Create Date: 2026-03-08 19:36:34.320385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '4a5b43769b29'
down_revision: Union[str, Sequence[str], None] = '5874714a69d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='chat_close_reason_enum',
        new_values=['BY_ADMIN', 'INACTIVITY'],
        affected_columns=[TableReference(table_schema='public', table_name='chats', column_name='close_reason')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='chat_close_reason_enum',
        new_values=['INACTIVITY'],
        affected_columns=[TableReference(table_schema='public', table_name='chats', column_name='close_reason')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
