"""Add status for places

Revision ID: c8054444741a
Revises: 7c70aa18f768
Create Date: 2026-04-10 19:00:21.384634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8054444741a'
down_revision: Union[str, Sequence[str], None] = '7c70aa18f768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'PUBLISHED', 'HIDDEN', name='place_status_enum').create(op.get_bind())
    op.add_column('places', sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'HIDDEN', name='place_status_enum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'status')
    sa.Enum('DRAFT', 'PUBLISHED', 'HIDDEN', name='place_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
