"""RESTRICT for places.id FK in route point

Revision ID: 56c0c9663e93
Revises: d8a09a98cee8
Create Date: 2026-04-10 20:02:02.601631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c0c9663e93'
down_revision: Union[str, Sequence[str], None] = 'd8a09a98cee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_route_points_place_id_places'), 'route_points', type_='foreignkey')
    op.create_foreign_key(op.f('fk_route_points_place_id_places'), 'route_points', 'places', ['place_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_route_points_place_id_places'), 'route_points', type_='foreignkey')
    op.create_foreign_key(op.f('fk_route_points_place_id_places'), 'route_points', 'places', ['place_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
