"""Make status for places required

Revision ID: d8a09a98cee8
Revises: c8054444741a
Create Date: 2026-04-10 19:01:04.338467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8a09a98cee8'
down_revision: Union[str, Sequence[str], None] = 'c8054444741a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'HIDDEN', name='place_status_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'HIDDEN', name='place_status_enum'),
               nullable=True)
    # ### end Alembic commands ###
