"""Make status for place categories required

Revision ID: 7c70aa18f768
Revises: d8ed3f0df5bc
Create Date: 2026-04-10 14:20:01.140870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c70aa18f768'
down_revision: Union[str, Sequence[str], None] = 'd8ed3f0df5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place_categories', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'HIDDEN', name='place_category_status_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place_categories', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'HIDDEN', name='place_category_status_enum'),
               nullable=True)
    # ### end Alembic commands ###
