"""Add status for place categories

Revision ID: d8ed3f0df5bc
Revises: f80ad1ab5531
Create Date: 2026-04-10 14:14:01.694775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8ed3f0df5bc'
down_revision: Union[str, Sequence[str], None] = 'f80ad1ab5531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'PUBLISHED', 'HIDDEN', name='place_category_status_enum').create(op.get_bind())
    op.add_column('place_categories', sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'HIDDEN', name='place_category_status_enum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_categories', 'status')
    sa.Enum('DRAFT', 'PUBLISHED', 'HIDDEN', name='place_category_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
