"""Add place_working_days table

Revision ID: bf31df061d65
Revises: 56c0c9663e93
Create Date: 2026-04-11 19:40:28.790286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf31df061d65'
down_revision: Union[str, Sequence[str], None] = '56c0c9663e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('UNSPECIFIED', 'CLOSED', 'OPEN', 'ALL_DAY', name='place_working_day_status_enum').create(op.get_bind())
    op.create_table('place_working_days',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('status', postgresql.ENUM('UNSPECIFIED', 'CLOSED', 'OPEN', 'ALL_DAY', name='place_working_day_status_enum', create_type=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weekday >= 1 AND weekday <= 7', name=op.f('ck_place_working_days_ck_pwd_weekday_range')),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_working_days_place_id_places'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_working_days')),
    sa.UniqueConstraint('place_id', 'weekday', name=op.f('uq_place_working_days_place_id'))
    )
    op.add_column('place_working_hours', sa.Column('working_day_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_place_working_hours_place_id'), 'place_working_hours', type_='unique')
    op.create_unique_constraint(op.f('uq_place_working_hours_working_day_id'), 'place_working_hours', ['working_day_id', 'start_time', 'end_time'])
    op.drop_constraint(op.f('fk_place_working_hours_place_id_places'), 'place_working_hours', type_='foreignkey')
    op.create_foreign_key(op.f('fk_place_working_hours_working_day_id_place_working_days'), 'place_working_hours', 'place_working_days', ['working_day_id'], ['id'], ondelete='CASCADE')
    op.drop_column('place_working_hours', 'weekday')
    op.drop_column('place_working_hours', 'place_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_working_hours', sa.Column('place_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('place_working_hours', sa.Column('weekday', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_place_working_hours_working_day_id_place_working_days'), 'place_working_hours', type_='foreignkey')
    op.create_foreign_key(op.f('fk_place_working_hours_place_id_places'), 'place_working_hours', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_place_working_hours_working_day_id'), 'place_working_hours', type_='unique')
    op.create_unique_constraint(op.f('uq_place_working_hours_place_id'), 'place_working_hours', ['place_id', 'weekday', 'start_time', 'end_time'], postgresql_nulls_not_distinct=False)
    op.drop_column('place_working_hours', 'working_day_id')
    op.drop_table('place_working_days')
    sa.Enum('UNSPECIFIED', 'CLOSED', 'OPEN', 'ALL_DAY', name='place_working_day_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
