"""Migrate to enum instead of str in place photos

Revision ID: 1ea7e7c599ba
Revises: 0aaa4ccc7bff
Create Date: 2026-04-12 13:11:40.113378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea7e7c599ba'
down_revision: Union[str, Sequence[str], None] = '0aaa4ccc7bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING_UPLOAD', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'DELETED', name='place_photo_status_enum').create(op.get_bind())
    op.alter_column('place_photos', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING_UPLOAD', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'DELETED', name='place_photo_status_enum'),
               existing_nullable=False,
               postgresql_using='status::place_photo_status_enum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place_photos', 'status',
               existing_type=sa.Enum('PENDING_UPLOAD', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'DELETED', name='place_photo_status_enum'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    sa.Enum('PENDING_UPLOAD', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'DELETED', name='place_photo_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
