"""Add new fields to place_photos

Revision ID: 0aaa4ccc7bff
Revises: bf31df061d65
Create Date: 2026-04-12 11:32:57.609654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aaa4ccc7bff'
down_revision: Union[str, Sequence[str], None] = 'bf31df061d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_photos', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('place_photos', sa.Column('original_filename', sa.String(length=512), nullable=True))
    op.add_column('place_photos', sa.Column('content_type', sa.String(length=128), nullable=True))
    op.add_column('place_photos', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('place_photos', sa.Column('upload_expires_at', sa.DateTime(), nullable=True))
    op.add_column('place_photos', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('place_photos', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.add_column('place_photos', sa.Column('failed_reason', sa.Text(), nullable=True))
    op.alter_column('place_photos', 'thumbnail_file_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.create_index(op.f('ix_place_photos_file_key'), 'place_photos', ['file_key'], unique=True)
    op.create_index(op.f('ix_place_photos_status'), 'place_photos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_photos_status'), table_name='place_photos')
    op.drop_index(op.f('ix_place_photos_file_key'), table_name='place_photos')
    op.alter_column('place_photos', 'thumbnail_file_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('place_photos', 'failed_reason')
    op.drop_column('place_photos', 'processed_at')
    op.drop_column('place_photos', 'uploaded_at')
    op.drop_column('place_photos', 'upload_expires_at')
    op.drop_column('place_photos', 'file_size')
    op.drop_column('place_photos', 'content_type')
    op.drop_column('place_photos', 'original_filename')
    op.drop_column('place_photos', 'status')
    # ### end Alembic commands ###
