"""Add staff_members table

Revision ID: c407a2aec848
Revises: 4a5b43769b29
Create Date: 2026-03-12 21:50:50.542849

"""
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c407a2aec848'
down_revision: Union[str, Sequence[str], None] = '4a5b43769b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('OWNER', 'ADMIN', 'SUPPORT', name='staff_role_enum').create(op.get_bind())
    op.create_table(
        'staff_members',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column(
            'role', postgresql.ENUM('OWNER', 'ADMIN', 'SUPPORT', name='staff_role_enum', create_type=False),
            nullable=False
            ),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_members')),
        sa.UniqueConstraint('email', name=op.f('uq_staff_members_email'))
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_members')
    sa.Enum('OWNER', 'ADMIN', 'SUPPORT', name='staff_role_enum').drop(op.get_bind())
    # ### end Alembic commands ###
