"""Remove unique at type

Revision ID: a797eb002f89
Revises: 9a9f8f6a8ee0
Create Date: 2026-03-13 19:47:21.026303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a797eb002f89'
down_revision: Union[str, Sequence[str], None] = '9a9f8f6a8ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_principals_type'), 'principals', type_='unique')
    op.create_index(op.f('ix_principals_type'), 'principals', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_principals_type'), table_name='principals')
    op.create_unique_constraint(op.f('uq_principals_type'), 'principals', ['type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
