"""Migrate from user_id to principal_id + principal_type

Revision ID: 9a9f8f6a8ee0
Revises: c407a2aec848
Create Date: 2026-03-13 19:24:13.305045

"""
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a9f8f6a8ee0'
down_revision: Union[str, Sequence[str], None] = 'c407a2aec848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER', 'STAFF', name='principal_type_enum').create(op.get_bind())
    op.create_table(
        'principals',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'type', postgresql.ENUM('USER', 'STAFF', name='principal_type_enum', create_type=False), nullable=False
            ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_principals')),
        sa.UniqueConstraint('type', name=op.f('uq_principals_type'))
        )
    op.add_column('auth_sessions', sa.Column('principal_id', sa.UUID(), nullable=False))
    op.add_column(
        'auth_sessions', sa.Column(
            'principal_type', postgresql.ENUM('USER', 'STAFF', name='principal_type_enum', create_type=False),
            nullable=False
            )
        )
    op.alter_column(
        'auth_sessions', 'device_id',
        existing_type=sa.UUID(),
        nullable=True
        )
    op.drop_index(
        op.f('ix_auth_sessions_user_device_revoked_at'), table_name='auth_sessions',
        postgresql_where='(revoked_at IS NOT NULL)'
        )
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.create_index(op.f('ix_auth_sessions_principal_id'), 'auth_sessions', ['principal_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_principal_type'), 'auth_sessions', ['principal_type'], unique=False)
    op.create_index(
        'ix_auth_sessions_principal_type_principal_id_active', 'auth_sessions', ['principal_type', 'principal_id'],
        unique=False, postgresql_where=sa.text('revoked_at IS NULL')
        )
    op.drop_constraint(op.f('fk_auth_sessions_user_id_users'), 'auth_sessions', type_='foreignkey')
    op.create_foreign_key(
        op.f('fk_auth_sessions_principal_id_principals'), 'auth_sessions', 'principals', ['principal_id'], ['id'],
        onupdate='CASCADE', ondelete='CASCADE'
        )
    op.drop_column('auth_sessions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_auth_sessions_principal_id_principals'), 'auth_sessions', type_='foreignkey')
    op.create_foreign_key(
        op.f('fk_auth_sessions_user_id_users'), 'auth_sessions', 'users', ['user_id'], ['id'], onupdate='CASCADE',
        ondelete='CASCADE'
        )
    op.drop_index(
        'ix_auth_sessions_principal_type_principal_id_active', table_name='auth_sessions',
        postgresql_where=sa.text('revoked_at IS NULL')
        )
    op.drop_index(op.f('ix_auth_sessions_principal_type'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_principal_id'), table_name='auth_sessions')
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_index(
        op.f('ix_auth_sessions_user_device_revoked_at'), 'auth_sessions', ['user_id', 'device_id'], unique=False,
        postgresql_where='(revoked_at IS NOT NULL)'
        )
    op.alter_column(
        'auth_sessions', 'device_id',
        existing_type=sa.UUID(),
        nullable=False
        )
    op.drop_column('auth_sessions', 'principal_type')
    op.drop_column('auth_sessions', 'principal_id')
    op.drop_table('principals')
    sa.Enum('USER', 'STAFF', name='principal_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
