"""Add foreign keys

Revision ID: e86be0d4931f
Revises: a797eb002f89
Create Date: 2026-03-13 19:53:59.515176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86be0d4931f'
down_revision: Union[str, Sequence[str], None] = 'a797eb002f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_staff_members_id_principals'), 'staff_members', 'principals', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_users_id_principals'), 'users', 'principals', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_id_principals'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_staff_members_id_principals'), 'staff_members', type_='foreignkey')
    # ### end Alembic commands ###
