"""Make route status not null

Revision ID: 13ed491a6074
Revises: 641674c473f7
Create Date: 2026-04-18 19:19:05.019326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13ed491a6074'
down_revision: Union[str, Sequence[str], None] = '641674c473f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'HIDDEN', name='route_status_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'HIDDEN', name='route_status_enum'),
               nullable=True)
    # ### end Alembic commands ###
