"""Add status for route

Revision ID: 641674c473f7
Revises: 1ea7e7c599ba
Create Date: 2026-04-18 19:18:01.890804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '641674c473f7'
down_revision: Union[str, Sequence[str], None] = '1ea7e7c599ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'PUBLISHED', 'HIDDEN', name='route_status_enum').create(op.get_bind())
    op.alter_column('route_translations', 'short_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('route_translations', 'description',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    op.add_column('routes', sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'HIDDEN', name='route_status_enum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'status')
    op.alter_column('route_translations', 'description',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    op.alter_column('route_translations', 'short_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    sa.Enum('DRAFT', 'PUBLISHED', 'HIDDEN', name='route_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
