"""Add devices table

Revision ID: 15de7b887626
Revises: 3c00cb6fd5fe
Create Date: 2026-02-20 23:34:04.668258

"""
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15de7b887626'
down_revision: Union[str, Sequence[str], None] = '3c00cb6fd5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'devices',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('platform', sa.Enum('ANDROID', name='device_platform_enum'), nullable=False),
        sa.Column('name', sa.VARCHAR(length=255), nullable=False),
        sa.Column('app_version', sa.VARCHAR(length=32), nullable=False),
        sa.Column('guest_user_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('last_seen_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['guest_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_devices_guest_user_id'), 'devices', ['guest_user_id'], unique=False)
    op.create_index(op.f('ix_devices_last_seen_at'), 'devices', ['last_seen_at'], unique=False)
    op.drop_index(op.f('ix_installations_user_id'), table_name='installations')
    op.drop_table('installations')
    op.add_column('refresh_sessions', sa.Column('device_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_refresh_sessions_device_id'), 'refresh_sessions', ['device_id'], unique=False)
    op.create_index(
        'ix_refresh_sessions_user_device_revoked_at', 'refresh_sessions', ['user_id', 'device_id'], unique=False,
        postgresql_where=sa.text('revoked_at IS NOT NULL')
        )
    op.create_foreign_key(None, 'refresh_sessions', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_sessions', type_='foreignkey')
    op.drop_index(
        'ix_refresh_sessions_user_device_revoked_at', table_name='refresh_sessions',
        postgresql_where=sa.text('revoked_at IS NOT NULL')
        )
    op.drop_index(op.f('ix_refresh_sessions_device_id'), table_name='refresh_sessions')
    op.drop_column('refresh_sessions', 'device_id')
    op.create_table(
        'installations',
        sa.Column('installation_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'extras', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"),
            autoincrement=False, nullable=False
            ),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False
            ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('installations_user_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('installation_id', name=op.f('installations_pkey'))
        )
    op.create_index(op.f('ix_installations_user_id'), 'installations', ['user_id'], unique=False)
    op.drop_index(op.f('ix_devices_last_seen_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_guest_user_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
