"""Add last_seen_at for users and created_at for installations

Revision ID: 0593d29a7646
Revises: 693859e081da
Create Date: 2026-02-20 17:50:35.872354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0593d29a7646'
down_revision: Union[str, Sequence[str], None] = '693859e081da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_installations_user_id'), 'installations', ['user_id'], unique=False)
    op.add_column('users', sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_users_last_seen_at'), 'users', ['last_seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_seen_at'), table_name='users')
    op.drop_column('users', 'last_seen_at')
    op.drop_index(op.f('ix_installations_user_id'), table_name='installations')
    op.drop_column('installations', 'created_at')
    # ### end Alembic commands ###
