"""Add metadata to installations table

Revision ID: 693859e081da
Revises: 24eb77f0fa1c
Create Date: 2026-02-20 17:39:06.281353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '693859e081da'
down_revision: Union[str, Sequence[str], None] = '24eb77f0fa1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installations', sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installations', 'extras')
    # ### end Alembic commands ###
