"""Refactor auth_sessions table

Revision ID: aaf6bbfe7dab
Revises: 7265f07c3188
Create Date: 2026-02-21 14:41:29.398160

"""
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aaf6bbfe7dab'
down_revision: Union[str, Sequence[str], None] = '7265f07c3188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auth_sessions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('device_id', sa.UUID(), nullable=False),
        sa.Column('refresh_token_hash', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_device_id'), 'auth_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_revoked_at'), 'auth_sessions', ['revoked_at'], unique=False)
    op.create_index(
        'ix_auth_sessions_user_device_revoked_at', 'auth_sessions', ['user_id', 'device_id'], unique=False,
        postgresql_where=sa.text('revoked_at IS NOT NULL')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_refresh_sessions_device_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_expires_at'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_revoked_at'), table_name='refresh_sessions')
    op.drop_index(
        op.f('ix_refresh_sessions_user_device_revoked_at'), table_name='refresh_sessions',
        postgresql_where='(revoked_at IS NOT NULL)'
    )
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'refresh_sessions',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('refresh_token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False
        ),
        sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['device_id'], ['devices.id'], name=op.f('refresh_sessions_device_id_fkey'), ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name=op.f('refresh_sessions_user_id_fkey'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('refresh_sessions_pkey')),
        sa.UniqueConstraint(
            'refresh_token_hash', name=op.f('refresh_sessions_refresh_token_hash_key'), postgresql_include=[],
            postgresql_nulls_not_distinct=False
        )
    )
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_index(
        op.f('ix_refresh_sessions_user_device_revoked_at'), 'refresh_sessions', ['user_id', 'device_id'], unique=False,
        postgresql_where='(revoked_at IS NOT NULL)'
    )
    op.create_index(op.f('ix_refresh_sessions_revoked_at'), 'refresh_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_expires_at'), 'refresh_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_device_id'), 'refresh_sessions', ['device_id'], unique=False)
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(
        'ix_auth_sessions_user_device_revoked_at', table_name='auth_sessions',
        postgresql_where=sa.text('revoked_at IS NOT NULL')
    )
    op.drop_index(op.f('ix_auth_sessions_revoked_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_device_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
