"""Refactor guest_user_id to users relationship (set null)

Revision ID: 71a8bf5b6b81
Revises: 386607b58662
Create Date: 2026-02-22 15:08:30.355194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a8bf5b6b81'
down_revision: Union[str, Sequence[str], None] = '386607b58662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('devices_guest_user_id_fkey'), 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'users', ['guest_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('devices_guest_user_id_fkey'), 'devices', 'users', ['guest_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
