"""Add reviews table

Revision ID: 8f0cebf95cbc
Revises: 4a5450520d2b
Create Date: 2026-02-27 20:26:53.825643

"""
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f0cebf95cbc'
down_revision: Union[str, Sequence[str], None] = '4a5450520d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reviews',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('author_id', sa.UUID(), nullable=False),
        sa.Column('entity_type', sa.Enum('PLACE', name='review_entity_type_enum'), nullable=False),
        sa.Column('entity_id', sa.UUID(), nullable=False),
        sa.Column('text', sa.VARCHAR(length=1000), nullable=True),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating_range'),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entity_type', 'entity_id', 'author_id', name='uq_reviews_entity_author')
        )
    op.create_index(op.f('ix_reviews_author_id'), 'reviews', ['author_id'], unique=False)
    op.create_index('ix_reviews_entity', 'reviews', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_reviews_entity_id'), 'reviews', ['entity_id'], unique=False)
    op.create_index(op.f('ix_reviews_entity_type'), 'reviews', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_entity_type'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_entity_id'), table_name='reviews')
    op.drop_index('ix_reviews_entity', table_name='reviews')
    op.drop_index(op.f('ix_reviews_author_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
