"""Add cascade update for all foreign keys

Revision ID: f534b6037703
Revises: 8f0cebf95cbc
Create Date: 2026-02-28 22:18:26.620585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f534b6037703'
down_revision: Union[str, Sequence[str], None] = '8f0cebf95cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('auth_sessions_user_id_fkey'), 'auth_sessions', type_='foreignkey')
    op.drop_constraint(op.f('auth_sessions_device_id_fkey'), 'auth_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'auth_sessions', 'devices', ['device_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'auth_sessions', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('devices_guest_user_id_fkey'), 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'users', ['guest_user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(op.f('reviews_author_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['author_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_author_id_fkey'), 'reviews', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('devices_guest_user_id_fkey'), 'devices', 'users', ['guest_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'auth_sessions', type_='foreignkey')
    op.drop_constraint(None, 'auth_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('auth_sessions_device_id_fkey'), 'auth_sessions', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('auth_sessions_user_id_fkey'), 'auth_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
