"""Add place phones table

Revision ID: 0e1cbbc4120f
Revises: c14abe3fd388
Create Date: 2026-03-30 12:42:22.229492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e1cbbc4120f'
down_revision: Union[str, Sequence[str], None] = 'c14abe3fd388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MOBILE', 'SUPPORT', 'LANDLINE', name='place_phone_type_enum').create(op.get_bind())
    op.create_table('place_phones',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('type', postgresql.ENUM('MOBILE', 'SUPPORT', 'LANDLINE', name='place_phone_type_enum', create_type=False), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_phones_place_id_places'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_phones')),
    sa.UniqueConstraint('place_id', 'number', name=op.f('uq_place_phones_place_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_phones')
    sa.Enum('MOBILE', 'SUPPORT', 'LANDLINE', name='place_phone_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
