"""Add tables for place categories

Revision ID: 7b3875897c26
Revises: e86be0d4931f
Create Date: 2026-03-30 11:02:06.162778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b3875897c26'
down_revision: Union[str, Sequence[str], None] = 'e86be0d4931f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_categories',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('icon_key', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_place_categories_slug'))
    )
    op.create_table('place_category_translations',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('language_code', postgresql.ENUM('ZH', 'EN', 'RU', name='language_enum', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['place_categories.id'], name=op.f('fk_place_category_translations_category_id_place_categories'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_category_translations')),
    sa.UniqueConstraint('category_id', 'language_code', name=op.f('uq_place_category_translations_category_id'))
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='user_role_enum',
        new_values=['USER', 'GUEST'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='user_role_enum',
        new_values=['ADMIN', 'USER', 'GUEST'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    op.drop_table('place_category_translations')
    op.drop_table('place_categories')
    # ### end Alembic commands ###
