"""Add routes and route_translations tables

Revision ID: 3907d5303552
Revises: eae3a078c764
Create Date: 2026-03-30 13:37:07.834260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3907d5303552'
down_revision: Union[str, Sequence[str], None] = 'eae3a078c764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_table('route_translations',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('language_code', postgresql.ENUM('ZH', 'EN', 'RU', name='language_enum', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_translations_route_id_routes'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_translations')),
    sa.UniqueConstraint('route_id', 'language_code', name=op.f('uq_route_translations_route_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_translations')
    op.drop_table('routes')
    # ### end Alembic commands ###
