"""Add route_points table

Revision ID: 22e47f50675a
Revises: 3907d5303552
Create Date: 2026-03-30 13:45:23.165585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e47f50675a'
down_revision: Union[str, Sequence[str], None] = '3907d5303552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_points',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_route_points_place_id_places'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_points_route_id_routes'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_points')),
    sa.UniqueConstraint('route_id', 'point_index', name=op.f('uq_route_points_route_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_points')
    # ### end Alembic commands ###
