"""Add translations table for places

Revision ID: c14abe3fd388
Revises: 68b94006f2e2
Create Date: 2026-03-30 12:27:08.032748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c14abe3fd388'
down_revision: Union[str, Sequence[str], None] = '68b94006f2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_translations',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('language_code', postgresql.ENUM('ZH', 'EN', 'RU', name='language_enum', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('address_display', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_translations_place_id_places'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_translations')),
    sa.UniqueConstraint('place_id', 'language_code', name=op.f('uq_place_translations_place_id'))
    )
    op.add_column('places', sa.Column('address_taxi', sa.String(length=255), nullable=True))
    op.add_column('places', sa.Column('address_taxi_comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'address_taxi_comment')
    op.drop_column('places', 'address_taxi')
    op.drop_table('place_translations')
    # ### end Alembic commands ###
