"""Add place working hours table

Revision ID: eae3a078c764
Revises: 0e1cbbc4120f
Create Date: 2026-03-30 13:09:25.144500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae3a078c764'
down_revision: Union[str, Sequence[str], None] = '0e1cbbc4120f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_working_hours',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_time <> end_time', name=op.f('ck_place_working_hours_ck_pwh_start_end_not_equal')),
    sa.CheckConstraint('weekday >= 1 AND weekday <= 7', name=op.f('ck_place_working_hours_ck_pwh_weekday_range')),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_working_hours_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_working_hours')),
    sa.UniqueConstraint('place_id', 'weekday', 'start_time', 'end_time', name=op.f('uq_place_working_hours_place_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_working_hours')
    # ### end Alembic commands ###
